keybindings:
  - keybinding: "Ctrl-Q"
    cursor_modes: ["buffer"]
    command: "quit"
  - keybinding: "Ctrl-C"
    cursor_modes: ["buffer"]
    command: "copy"
  - keybinding: "Ctrl-V"
    cursor_modes: ["buffer"]
    command: "paste"
  - keybinding: "Ctrl-S"
    cursor_modes: ["buffer"]
    command: "save"
  - keybinding: "Ctrl-O"
    cursor_modes: ["buffer"]
    command: "open"
  - keybinding: "Ctrl-R"
    cursor_modes: ["buffer"]
    command: "reload"
  - keybinding: "PgUp"
    cursor_modes: ["buffer"]
    command: "prev-buffer"
  - keybinding: "PgDn"
    cursor_modes: ["buffer"]
    command: "next-buffer"
  - keybinding: "Ctrl-N"
    cursor_modes: ["buffer"]
    command: "new-buffer"
  - keybinding: "Delete"
    cursor_modes: ["buffer"]
    command: "close-buffer"
  - keybinding: "F1"
    cursor_modes: ["buffer","dropdown"]
    command: "menu-file"
  - keybinding: "F2"
    cursor_modes: ["buffer","dropdown"]
    command: "menu-edit"
  - keybinding: "F3"
    cursor_modes: ["buffer","dropdown"]
    command: "menu-buffers"
  - keybinding: "Ctrl-E"
    cursor_modes: ["buffer"]
    command: "execute"